base_url = "https://hitblast.fun"

compile_sass = true

build_search_index = true

taxonomies = [{ name = "tags", feed = true }]
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
external_links_target_blank = true

[markdown.highlighting]
theme = "min-dark"
